apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: root-app
  namespace: argocd
spec:
  description: Root project for Argo CD applications
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
