apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: root-app
  source:
    repoURL: https://github.com/Ajay0696/Cluster-Addons-Argo-CD.git
    targetRevision: HEAD
    path: Projects  # This is where your child app yamls live
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
